name: Build Pipeline

run-name: 'Build Pipeline For ${{github.ref_name}}'

on:
    pull_request_target:

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
          - name: Checkout Code Repository
            uses: actions/checkout@v4
          - name: Downloading Java
            uses: actions/setup-java@v4
            with:
                java-version: '21'
                distribution: 'temurin'
          - name: Maven Build
            if: github.ref == 'refs/heads/main'
            run: |
              java --version
              mvn clean install \
                --batch-mode \
                -e \
                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                -PcodeQuality
          - name: Maven Build -- Feature Branch
            if: github.ref != 'refs/heads/main'
            run: |
              java --version
              mvn clean install \
                --batch-mode \
                -e \
                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                -PcodeQuality
  publish-to-artifact-repositories:
      name: Publish To Nexus
      runs-on: ubuntu-latest
      needs: build-job
      env:
        REPOSITORY_ID: "maven-snapshots"
      steps:
        - name: Checkout Code Repository
          uses: actions/checkout@v4
        - name: Downloading Java
          uses: actions/setup-java@v4
          with:
              java-version: '21'
              distribution: 'temurin'
        - name: Settings.xml Config
          uses: s4u/maven-settings-action@v2.3.0
          with:
             servers: |
                  [{
                      "id": "${{vars.NEXUS_SNAPSHOT_REPO_ID}}",
                      "username": "${{ vars.NEXUS_USERNAME }}",
                      "password": "${{ secrets.NEXUS_PASSWORD}}"
                  }] 
        - name: Deploy To Nexus
          run: |
             mvn deploy \
                --batch-mode \
                -e \
                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                -DskipTests \
                -DskipITs \
                -Dmaven.main.skip \
                -Dmaven.test.skip \
                -s '/home/runner/.m2/settings.xml' \
                -DrepositoryId='maven-snapshots' \
                -Dgpg.passphrase= ${{secrets.GPG_PASSPHRASE}}