name: Build Workflow

run-name: 'Build Workflow For ${{github.ref_name}}'

on:
    push:

jobs:
  build-job:
    name: Build Job
    runs-on: self-hosted
    steps:
          - name: Checkout Code Repository
            uses: actions/checkout@v4
          - name: Downloading Java
            uses: actions/setup-java@v4
            with:
                java-version: '21'
                distribution: 'adopt'
          - name: Download Maven
            run: |
                  curl -sL https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip -o maven.zip
                  sudo yum update
                  sudo yum -y install unzip
                  unzip -d /usr/share maven.zip
                  rm maven.zip
                  ln -s /usr/share/apache-maven-3.6.3/bin/mvn /usr/bin/mvn
                  echo "M2_HOME=/usr/share/apache-maven-3.6.3" | tee -a /etc/environment
          - name: Maven Build
            if: github.ref == 'refs/heads/main'
            run: |
              java --version
              mvn clean install \
                --batch-mode \
                -e \
                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                -PcodeQuality
          - name: Maven Build -- Feature Branch
            if: github.ref != 'refs/heads/main'
            run: |
              java --version
              mvn clean install \
                --batch-mode \
                -e \
                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                -PcodeQuality
          - name: Settings.xml Config
            uses: whelk-io/maven-settings-xml-action@v22
            with:
                servers: > 
                        [
                          {
                            "id": "nexus"
                          },
                          {
                            "id": "${{vars.NEXUS_SNAPSHOT_REPO_ID}}",
                            "username": "${{ vars.NEXUS_USERNAME }}",
                            "password": "${{ secrets.NEXUS_PASSWORD}}"
                          },
                          {
                            "id": "${{vars.NEXUS_MIRROR_ID}}",
                            "username": "${{ vars.NEXUS_USERNAME }}",
                            "password": "${{ secrets.NEXUS_PASSWORD}}"
                          }
                        ] 
                profiles: >
                       [{
                            "id": "inject-application-properties",
                            "properties": {
                                "altSnapshotDeploymentRepository": "${{vars.NEXUS_SNAPSHOT_REPO_ID}}::${{vars.NEXUS_SNAPSHOT_REPO_URL}}",
                                "altReleaseDeploymentRepository": "${{vars.NEXUS_RELEASE_REPO_ID}}::${{vars.NEXUS_RELEASE_REPO_URL}}"
                            }
                       }]
                active_profiles: > 
                       [
                          "inject-application-properties"
                       ]
                mirrors: >
                       [{
                           "id": "${{vars.NEXUS_MIRROR_ID}}",
                           "name": "${{vars.NEXUS_MIRROR_ID}}",
                           "url": "${{vars.NEXUS_MIRROR_URL}}",
                           "mirrorOf": "*"
                       }]
                output_file: .m2/settings.xml
          - name: Deploy To Nexus
            run: |
                   sudo curl https://nexus.build.tinkarbuild.com
                   mvn deploy \
                      --batch-mode \
                      -e \
                      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                      -DskipTests \
                      -DskipITs \
                      -Dmaven.main.skip \
                      -Dmaven.test.skip \
                      -s '/home/runner/work/build-parent/build-parent/.m2/settings.xml' \
                      -DrepositoryId='maven-snapshots' \
                      -Dgpg.passphrase=${{secrets.GPG_PASSPHRASE}}
