name: Publish Pipeline

run-name: 'Publish Artifacts'

on:
   workflow_run:
    workflows:
      - Build Workflow
      - Release Workflow
    types:
      - completed
        
        
jobs:
  publish-artifacts:
      name: Publish Artifacts
      runs-on: ubuntu-latest
      if: github.event.workflow_run.conclusion == 'success'
      env:
        ARTIFACT_REPOSITORY_ID: "maven-releases"
        REPOSITORY_NAME: ${{github.repository}}
        BRANCH: "main"  
      steps:
        - name: If Pull Request Then Update Env
          if: github.event.workflow_run.event == 'pull_request'
          run: |
            echo "REPOSITORY_NAME=${{github.actor}}/${{github.event.repository.name}}" >> $GITHUB_ENV
            echo "BRANCH=${{github.event.workflow_run.head_branch}}" >> $GITHUB_ENV
            echo "ARTIFACT_REPOSITORY_ID=maven-snapshots" >> $GITHUB_ENV
        
        - name: Checkout Forked Code Repository
          uses: actions/checkout@v4
          if:   github.event.workflow_run.event == 'pull_request'
          with:
            repository: ${{env.REPOSITORY_NAME}}
            ref: ${{env.BRANCH}}

        - name: Checkout Code Repository
          if:   github.event.workflow_run.event != 'pull_request'
          uses: actions/checkout@v4

        - name: Downloading Java
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'adopt'

        - name: Publish To Nexus Repository Manager
          run: echo "Publishing to Nexus Repo -- ${{env.ARTIFACT_REPOSITORY_ID}}"

        - name: Publish To OSSRH (Maven Central Staging)
          if: github.event.workflow.name == 'Release Workflow'
          run: echo "Publishint to OSSRH Repo -- ${{env.ARTIFACT_REPOSITORY_ID}}"

  


          
            



  

        