name: Tag Workflow

run-name: 'Tag Workflow'

on:
    workflow_dispatch:

env:
    MAVEN_SETTING: '/home/ec2-user/maven/.m2/settings.xml'

jobs:
  build-tag:
    name: Build Tag
    runs-on: self-hosted
    if: github.repository_owner == 'ikmdev'
    steps:
          - name: Checkout Code Repository
            uses: actions/checkout@v4
            with:
                ref: ${{github.ref}}

          - name: Setup Maven Action
            uses: s4u/setup-maven-action@v1.14.0
            with:
              checkout-fetch-depth: 0
              java-version: 21
              java-distribution: adopt
              maven-version: 3.9.0

          - name: Maven Build
            run: |
              mvn clean install \
                -s ${{env.MAVEN_SETTING}} \
                --batch-mode \
                -e \
                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                -PcodeQuality

          - name: Deploy To Nexus
            run: |
              mvn deploy \
                    --batch-mode \
                    -e \
                    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                    -DskipTests \
                    -DskipITs \
                    -Dmaven.main.skip \
                    -Dmaven.test.skip \
                    -s ${{env.MAVEN_SETTING}} \
                    -DrepositoryId='maven-releases' \
                    -Dgpg.passphrase=${{secrets.GPG_PASSPHRASE}}
      
      
          - name: Publish To OSSRH (Maven Central Staging)
            if: github.event.workflow.name == 'Release Workflow'
            run: |
                mvn deploy \
                    --batch-mode \
                    -e \
                    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                    -DskipTests \
                    -DskipITs \
                    -Dmaven.main.skip \
                    -Dmaven.test.skip \
                    -s ${{env.MAVEN_SETTING}} \
                    -DrepositoryId='maven-releases' \
                    -DrepositoryIdOSSRH='true' \
                    -PstageOSSRH -Dgpg.passphrase='${{secrets.GPG_PASSPHRASE}}'
